using System.Collections.Generic;
using System.IO;
using System.Text;
using NUnit.Framework;
using RCore.SheetX.Editor;
using UnityEditor;
using UnityEngine;

namespace RCore.SheetX.Tests
{
	public class CollectionDepthChangeTests
	{
		private const string TestRoot = "Assets/SheetXDepthTemp";
		private const string CodeFolder = TestRoot + "/Code";
		private const string SourceId = "depth.xlsx";

		[SetUp]
		public void SetUp()
		{
			AssetDatabase.DeleteAsset(TestRoot);
			if (!AssetDatabase.IsValidFolder(TestRoot))
				AssetDatabase.CreateFolder("Assets", "SheetXDepthTemp");
			if (!AssetDatabase.IsValidFolder(CodeFolder))
				AssetDatabase.CreateFolder(TestRoot, "Code");
		}

		[TearDown]
		public void TearDown()
		{
			AssetDatabase.DeleteAsset(TestRoot);
			// The export session writes real files through SheetXFileOutput, which the asset
			// database may not know about yet.
			if (Directory.Exists(TestRoot))
				Directory.Delete(TestRoot, true);
			if (File.Exists(TestRoot + ".meta"))
				File.Delete(TestRoot + ".meta");
			AssetDatabase.Refresh();
		}

		[Test]
		public void depth_change_is_detected_from_the_generated_declaration_on_disk()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				// The file on disk still says SeparateAsset; settings now say Inline.
				WriteGenerated("public partial class PlayerConfigCollection : SheetXConfigCollectionBase");

				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings),
					Is.EqualTo(new[] { "Player" }));
			}
			finally
			{
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void matching_depth_and_missing_file_are_not_changes()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				// No generated file yet: a first export is not a depth change.
				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings), Is.Empty);

				WriteGenerated("[Serializable]\r\npublic partial class PlayerConfigCollection");
				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings), Is.Empty);
			}
			finally
			{
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void separate_asset_matching_the_generated_declaration_is_not_a_change()
		{
			// The default path, and the one every existing project sits on: settings say
			// SeparateAsset and the file on disk declares the asset base type. Zero changes, so
			// no migration prompt on an export that changes nothing.
			var settings = CreateSettings(SheetXCollectionDepth.SeparateAsset);
			try
			{
				WriteGenerated("public partial class PlayerConfigCollection : SheetXConfigCollectionBase");

				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings), Is.Empty);
			}
			finally
			{
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void reverting_to_separate_asset_is_also_a_change()
		{
			var settings = CreateSettings(SheetXCollectionDepth.SeparateAsset);
			try
			{
				WriteGenerated("[Serializable]\r\npublic partial class PlayerConfigCollection");

				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings),
					Is.EqualTo(new[] { "Player" }));
			}
			finally
			{
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void global_collection_is_never_reported_as_depth_change_even_without_builtin_flag()
		{
			var settings = ScriptableObject.CreateInstance<SheetXSettings>();
			try
			{
				settings.enableCollections = true;
				settings.collectionCodeFolder = CodeFolder;
				settings.collections = new List<SheetXCollectionDefinition>
				{
					new SheetXCollectionDefinition { name = "Global", builtInGlobal = false }
				};

				File.WriteAllText(
					CodeFolder + "/GlobalConfigCollection.cs",
					"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\npublic partial class GlobalConfigCollection : GlobalConfigCollectionBase\r\n{\r\n}\r\n");

				Assert.That(SheetXCollectionSettings.DetectDepthChanges(settings), Is.Empty);
			}
			finally
			{
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void migration_snapshot_restores_the_previous_generated_sources()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				string path = CodeFolder + "/PlayerConfigCollection.cs";
				const string previous =
					"public partial class PlayerConfigCollection : SheetXConfigCollectionBase\r\n{\r\n}\r\n";
				File.WriteAllText(path, previous);

				SheetXMigrationSnapshot.Capture(
					settings,
					new[] { "Player" },
					new Dictionary<string, string> { [path] = previous });

				// The migration proceeds and the new source lands, then the bake fails after the reload.
				File.WriteAllText(path, "[Serializable]\r\npublic partial class PlayerConfigCollection\r\n{\r\n}\r\n");
				Assert.That(SheetXMigrationSnapshot.Exists, Is.True);

				Assert.That(SheetXMigrationSnapshot.TryRestore(out string error), Is.True, error);

				// Sources go back first; the types they declare recompile before any asset is touched.
				Assert.That(File.ReadAllText(path), Is.EqualTo(previous));
				Assert.That(SheetXMigrationSnapshot.Exists, Is.False);
			}
			finally
			{
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void clearing_a_pending_snapshot_removes_it()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				SheetXMigrationSnapshot.Capture(settings, new[] { "Player" }, new Dictionary<string, string>());
				Assert.That(SheetXMigrationSnapshot.Exists, Is.True);

				SheetXMigrationSnapshot.Clear();

				Assert.That(SheetXMigrationSnapshot.Exists, Is.False);
			}
			finally
			{
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void peek_names_the_collections_a_pending_snapshot_would_revert()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				SheetXMigrationSnapshot.Clear();
				Assert.That(SheetXMigrationSnapshot.TryPeek(out var none, out _), Is.False);
				Assert.That(none, Is.Empty);

				string path = CodeFolder + "/PlayerConfigCollection.cs";
				SheetXMigrationSnapshot.Capture(
					settings,
					new[] { "Player" },
					new Dictionary<string, string> { [path] = "public partial class PlayerConfigCollection\r\n{\r\n}\r\n" });

				// The names are what a confirmation prompt shows, so a snapshot left over from an
				// earlier migration is visible as the wrong collection before anything is reverted.
				Assert.That(SheetXMigrationSnapshot.TryPeek(out var collections, out string settingsPath), Is.True);
				Assert.That(collections, Is.EqualTo(new[] { "Player" }));
				Assert.That(settingsPath, Is.Not.Null);

				// Peeking is read-only: the snapshot is still there to restore.
				Assert.That(SheetXMigrationSnapshot.Exists, Is.True);
			}
			finally
			{
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void restore_writes_the_original_bytes_and_never_a_bom()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			try
			{
				string path = CodeFolder + "/PlayerConfigCollection.cs";
				// Non-ASCII in a comment: a byte comparison catches an encoding change that a string
				// comparison would silently normalise away.
				const string previous =
					"/*** cấu hình ***/\r\npublic partial class PlayerConfigCollection : SheetXConfigCollectionBase\r\n{\r\n}\r\n";
				File.WriteAllText(path, previous);

				SheetXMigrationSnapshot.Capture(
					settings,
					new[] { "Player" },
					new Dictionary<string, string> { [path] = previous });
				File.WriteAllText(path, "[Serializable]\r\npublic partial class PlayerConfigCollection\r\n{\r\n}\r\n");

				Assert.That(SheetXMigrationSnapshot.TryRestore(out string error), Is.True, error);

				byte[] restored = File.ReadAllBytes(path);
				Assert.That(restored, Is.Not.Empty, "A restored source must never be left empty.");
				// The 1.8.0 release removed BOMs from generated output; a restored file gaining one
				// would no longer match what the generator emits for the same collection.
				Assert.That(restored.Length >= 3 && restored[0] == 0xEF && restored[1] == 0xBB && restored[2] == 0xBF,
					Is.False, "Restore must not introduce a UTF-8 BOM.");
				Assert.That(restored, Is.EqualTo(new UTF8Encoding(false).GetBytes(previous)));

				// The swap leaves no scratch file behind for the asset database to import as a script.
				Assert.That(File.Exists(path + ".tmp"), Is.False);
			}
			finally
			{
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void a_later_sweep_for_another_settings_asset_leaves_the_snapshot_alone()
		{
			// Sweep 1 failed on asset A, so the snapshot survives and A is not re-queued. Sweep 2 is
			// an unrelated export of asset B that succeeds cleanly: it must not delete A's only
			// recovery route.
			const string ownerPath = "Assets/A/SheetXSettings.asset";
			const string otherPath = "Assets/B/SheetXSettings.asset";

			Assert.That(SheetXCollectionBaker.ShouldClearSnapshot(
				false, 0, new[] { otherPath }, ownerPath), Is.False);

			// The sweep that actually re-bakes the migrated asset does retire it.
			Assert.That(SheetXCollectionBaker.ShouldClearSnapshot(
				false, 0, new[] { otherPath, ownerPath }, ownerPath), Is.True);

			// No snapshot at all: unchanged behaviour, Clear() is a no-op anyway.
			Assert.That(SheetXCollectionBaker.ShouldClearSnapshot(
				false, 0, new[] { otherPath }, null), Is.True);

			// A failure or a re-queued entry still blocks the clear, snapshot owner or not.
			Assert.That(SheetXCollectionBaker.ShouldClearSnapshot(
				true, 0, new[] { ownerPath }, ownerPath), Is.False);
			Assert.That(SheetXCollectionBaker.ShouldClearSnapshot(
				false, 1, new[] { ownerPath }, ownerPath), Is.False);
		}

		[Test]
		public void restore_without_a_snapshot_reports_instead_of_throwing()
		{
			SheetXMigrationSnapshot.Clear();

			Assert.That(SheetXMigrationSnapshot.TryRestore(out string error), Is.False);
			Assert.That(error, Does.Contain("No migration snapshot"));
		}

		[Test]
		public void flush_captures_the_snapshot_before_the_new_sources_are_written()
		{
			var settings = SessionSettings();
			var confirm = SheetXCollectionExportSession.ConfirmDepthChange;
			// Flush now asks before migrating; an interactive Editor run would block on the dialog.
			SheetXCollectionExportSession.ConfirmDepthChange = _ => true;
			try
			{
				string path = CodeFolder + "/PlayerConfigCollection.cs";
				// On disk the collection is still SeparateAsset; settings now say Inline, so the
				// flush below is a depth migration and must snapshot THIS text, not what replaces it.
				const string previous =
					"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\npublic partial class PlayerConfigCollection : SheetXConfigCollectionBase\r\n{\r\n}\r\n";
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(path, previous);

				var binding = SheetXCollectionSettings.GetOrCreateBinding(settings, SourceId, "PlayerTable");
				binding.outputMode = SheetXSheetOutputMode.GeneratedDataClass;
				binding.collectionName = "Player";

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "PlayerTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				// The flush replaced the file: the snapshot is worthless unless it was taken first.
				Assert.That(File.ReadAllText(path), Is.Not.EqualTo(previous));
				Assert.That(SheetXMigrationSnapshot.Exists, Is.True,
					"A depth change must capture a snapshot during Flush.");

				Assert.That(SheetXMigrationSnapshot.TryRestore(out error), Is.True, error);
				Assert.That(File.ReadAllText(path), Is.EqualTo(previous),
					"Capture must run before the generated sources are written.");
			}
			finally
			{
				SheetXCollectionExportSession.ConfirmDepthChange = confirm;
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void declining_a_depth_change_aborts_the_flush_before_anything_is_written()
		{
			var settings = SessionSettings();
			var confirm = SheetXCollectionExportSession.ConfirmDepthChange;
			var prompted = new List<string>();
			SheetXCollectionExportSession.ConfirmDepthChange = message =>
			{
				prompted.Add(message);
				return false;
			};
			try
			{
				string path = CodeFolder + "/PlayerConfigCollection.cs";
				const string previous =
					"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\npublic partial class PlayerConfigCollection : SheetXConfigCollectionBase\r\n{\r\n}\r\n";
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(path, previous);

				var binding = SheetXCollectionSettings.GetOrCreateBinding(settings, SourceId, "PlayerTable");
				binding.outputMode = SheetXSheetOutputMode.GeneratedDataClass;
				binding.collectionName = "Player";

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "PlayerTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);

				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("was not confirmed"));
				Assert.That(prompted, Has.Count.EqualTo(1));

				// Declining must abort ahead of every side effect: the sources on disk are untouched
				// and no snapshot was taken, so there is nothing left to roll back or clean up.
				Assert.That(File.ReadAllText(path), Is.EqualTo(previous));
				Assert.That(SheetXMigrationSnapshot.Exists, Is.False);
			}
			finally
			{
				SheetXCollectionExportSession.ConfirmDepthChange = confirm;
				SheetXMigrationSnapshot.Clear();
				Object.DestroyImmediate(settings);
			}
		}

		[Test]
		public void depth_change_prompt_is_injectable_and_names_the_collection()
		{
			var captured = new List<string>();
			var original = SheetXCollectionExportSession.ConfirmDepthChange;
			try
			{
				SheetXCollectionExportSession.ConfirmDepthChange = message =>
				{
					captured.Add(message);
					return false;
				};

				// A headless or test run must never block on EditorUtility.DisplayDialog.
				Assert.That(SheetXCollectionExportSession.ConfirmDepthChange("Player"), Is.False);
				Assert.That(captured, Has.Count.EqualTo(1));
				Assert.That(captured[0], Does.Contain("Player"));
			}
			finally
			{
				SheetXCollectionExportSession.ConfirmDepthChange = original;
			}
		}

		[Test]
		public void default_depth_change_prompt_is_wired_up()
		{
			Assert.That(SheetXCollectionExportSession.ConfirmDepthChange, Is.Not.Null);
		}

		private static SheetXSettings SessionSettings()
		{
			var settings = CreateSettings(SheetXCollectionDepth.Inline);
			settings.collectionNamespace = "Game.DepthConfig";
			settings.collectionJsonFolder = TestRoot + "/Json";
			settings.collectionAssetFolder = TestRoot + "/Collections";
			settings.globalResourcesFolder = TestRoot + "/Resources";
			return settings;
		}

		private static void WriteGenerated(string declaration)
		{
			File.WriteAllText(
				CodeFolder + "/PlayerConfigCollection.cs",
				"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\n" + declaration + "\r\n{\r\n}\r\n");
		}

		private static SheetXSettings CreateSettings(SheetXCollectionDepth depth)
		{
			var settings = ScriptableObject.CreateInstance<SheetXSettings>();
			settings.ResetToDefault();
			settings.enableCollections = true;
			settings.collectionCodeFolder = CodeFolder;
			settings.collections.Add(new SheetXCollectionDefinition { name = "Player", depth = depth });
			return settings;
		}
	}
}
