using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using RCore.SheetX.Editor;
using UnityEditor;
using UnityEngine;

namespace RCore.SheetX.Tests
{
	/// <summary>Stands in for a row type a consuming project owns, for Existing Data Class coverage.</summary>
	[Serializable, SheetXBindable]
	public sealed class CollectionGenerationExistingRow
	{
		public int id;
		public string name;
	}

	public class CollectionGenerationTests
	{
		[Test]
		public void generator_uses_plain_cs_filename_and_sheetx_banner()
		{
			var settings = Settings();
			try
			{
				string source = SheetXCollectionGenerator.Emit(
					settings, Array.Empty<SheetXCollectionGeneratedTable>());

				Assert.That(SheetXCollectionGenerator.FileName,
					Is.EqualTo("SheetXDataCollections.cs"));
				Assert.That(source, Does.StartWith(
					"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\n"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_emits_data_and_matching_collection_scripts()
		{
			var settings = Settings();
			try
			{
				var files = SheetXCollectionGenerator.EmitFiles(settings, new[]
				{
					Generated("excel-b", "ShopItems", "Shop", "shopItems",
						"id:int", "tags[]:string", "reward.amount:int"),
					Existing("google-a", "Missions", "Shop", "missions", "MissionData"),
					Generated("excel-a", "GameSettings", "Global", "gameSettings", "key:string"),
				});
				string dataSource = files[SheetXCollectionGenerator.FileName];
				string globalSource = files["GlobalConfigCollection.cs"];
				string shopSource = files["ShopConfigCollection.cs"];

				Assert.That(dataSource, Does.Contain("public partial class ShopItemsSX"));
				Assert.That(dataSource, Does.Contain("public int id;"));
				Assert.That(dataSource, Does.Contain("public string[] tags;"));
				Assert.That(dataSource, Does.Contain("public Reward reward;"));
				Assert.That(dataSource, Does.Contain(
					"internal const string ShopItems = \"Assets/Game/DataConfig/Editor/Json/ShopItems.txt\";"));
				Assert.That(dataSource, Does.Not.Contain("ConfigCollection :"));

				Assert.That(shopSource, Does.Contain(
					"public partial class ShopConfigCollection : SheetXConfigCollectionBase"));
				Assert.That(shopSource, Does.Contain("public ShopItemsSX[] shopItems;"));
				Assert.That(shopSource, Does.Contain("public MissionData[] missions;"));
				Assert.That(globalSource, Does.Contain(
					"public partial class GlobalConfigCollection : GlobalConfigCollectionBase"));
				Assert.That(globalSource, Does.Contain("public ShopConfigCollection shop;"));

				Assert.That(files.Keys, Is.EqualTo(new[]
				{
					"SheetXDataCollections.cs",
					"GlobalConfigCollection.cs",
					"ShopConfigCollection.cs",
				}));
				foreach (string source in files.Values)
				{
					Assert.That(source, Does.StartWith(
						"/***\r\n * This script is automatically generated by SheetX.\r\n ***/\r\n"));
					Assert.That(source, Does.Contain("using RCore.SheetX;"));
					Assert.That(source, Does.Not.Contain("UnityEditor"));
					Assert.That(source, Does.Not.Contain("Newtonsoft"));
					Assert.That(source.Replace("\r\n", ""), Does.Not.Contain("\n"));
				}
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_stamps_each_table_with_the_json_path_it_emitted()
		{
			var settings = Settings();
			try
			{
				var table = Existing("a", "Shop Items", "Shop", "shopItems", "ShopItemsRow");

				SheetXCollectionGenerator.Emit(settings, new[] { table });

				Assert.That(table.JsonPath, Is.EqualTo("Assets/Game/DataConfig/Editor/Json/Shop_Items.txt"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_orders_collection_files_and_table_fields_ordinally()
		{
			var settings = Settings();
			try
			{
				var files = SheetXCollectionGenerator.EmitFiles(settings, new[]
				{
					Existing("z", "Zulu", "Shop", "zulu", "ZuluRow"),
					Existing("b", "Beta", "Global", "beta", "BetaRow"),
					Existing("a", "Alpha", "Global", "alpha", "AlphaRow"),
					Existing("a", "AlphaFeature", "Audio", "alphaFeature", "AlphaFeatureRow"),
				});

				Assert.That(files.Keys, Is.EqualTo(new[]
				{
					"SheetXDataCollections.cs",
					"GlobalConfigCollection.cs",
					"AudioConfigCollection.cs",
					"ShopConfigCollection.cs",
				}));
				string globalSource = files["GlobalConfigCollection.cs"];
				Assert.That(IndexOf(globalSource, "public AlphaRow[] alpha;"),
					Is.LessThan(IndexOf(globalSource, "public BetaRow[] beta;")));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_emits_empty_defined_collection_and_global_reference()
		{
			var settings = Settings();
			try
			{
				settings.collections.Add(new SheetXCollectionDefinition { name = "Shop" });

				var files = SheetXCollectionGenerator.EmitFiles(settings,
					new[] { Existing("a", "Items", "Global", "items", "ItemRow") });

				Assert.That(files["ShopConfigCollection.cs"],
					Does.Contain("class ShopConfigCollection : SheetXConfigCollectionBase"));
				Assert.That(files["GlobalConfigCollection.cs"],
					Does.Contain("public ShopConfigCollection shop;"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_rejects_row_type_collision_after_sheet_normalization()
		{
			var settings = Settings();
			try
			{
				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[]
					{
						Generated("a", "Shop Items", "Global", "shopItemsA", "id:int"),
						Generated("b", "ShopItems", "Shop", "shopItemsB", "id:int"),
					}),
					Throws.TypeOf<InvalidOperationException>().With.Message.Contains("ShopItemsSX"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_rejects_duplicate_field_and_path_constant_names()
		{
			var settings = Settings();
			try
			{
				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[]
					{
						Existing("a", "One", "Shop", "items", "OneRow"),
						Existing("b", "Two", "Shop", "items", "TwoRow"),
					}),
					Throws.TypeOf<InvalidOperationException>().With.Message.Contains("declares field 'items' twice"));

				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[]
					{
						Existing("a", "Shop Items", "Global", "itemsA", "OneRow"),
						Existing("b", "ShopItems", "Shop", "itemsB", "TwoRow"),
					}),
					Throws.TypeOf<InvalidOperationException>().With.Message.Contains("path constant 'ShopItems'"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_rejects_global_table_field_that_shadows_a_feature_reference()
		{
			var settings = Settings();
			try
			{
				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[]
					{
						Existing("a", "Shop", "Global", "shop", "ShopRow"),
						Existing("b", "ShopItems", "Shop", "shopItems", "ShopItemsRow"),
					}),
					Throws.TypeOf<InvalidOperationException>().With.Message
						.Contains("Global table field 'shop' collides with feature collection reference 'Shop'"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void generator_rejects_generated_type_named_after_the_path_constants_class()
		{
			var settings = Settings();
			try
			{
				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[]
					{
						Generated("a", "Items", "Global", "items", "sheetXCollectionPaths.id:int"),
					}),
					Throws.TypeOf<InvalidOperationException>().With.Message.Contains("SheetXCollectionPaths"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void json_only_binding_produces_no_generated_table_declaration()
		{
			var settings = Settings();
			try
			{
				var tables = new List<SheetXCollectionGeneratedTable>();
				var binding = new SheetXSheetBinding
				{
					outputMode = SheetXSheetOutputMode.JsonOnly,
					sheetName = "RawData",
				};
				if (binding.outputMode != SheetXSheetOutputMode.JsonOnly)
					tables.Add(Existing("source", binding.sheetName, "Global", "rawData", "RawDataRow"));

				string source = SheetXCollectionGenerator.Emit(settings, tables);

				Assert.That(source, Does.Not.Contain("RawData"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_places_configuration_members_directly_in_global()
		{
			var settings = Settings();
			try
			{
				var files = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration());
				string source = files["GlobalConfigCollection.cs"];

				Assert.That(source, Does.Contain("[Serializable]"));
				Assert.That(source, Does.Contain("public class Economy"));
				Assert.That(source, Does.Contain("public int startingCoins;"));
				Assert.That(source, Does.Contain("public Economy economy;"));
				Assert.That(source, Does.Contain("public Vector2 position2;"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_omits_standalone_configuration_contract()
		{
			var settings = Settings();
			try
			{
				string source = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration())["GlobalConfigCollection.cs"];

				Assert.That(source, Does.Not.Contain("class Configuration"));
				Assert.That(source, Does.Not.Contain("configJson"));
				Assert.That(source, Does.Not.Contain("autoLoad"));
				Assert.That(source, Does.Not.Contain("Load()"));
				Assert.That(source, Does.Not.Contain("ContextMenu"));
				Assert.That(source, Does.Not.Contain("TextAsset"));
				Assert.That(source, Does.Not.Contain("UnityEditor"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_adds_configuration_path_marker_when_present()
		{
			var settings = Settings();
			try
			{
				string source = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration())[SheetXCollectionGenerator.FileName];

				Assert.That(source, Does.Contain(
					"internal const string Configuration = \"Assets/Game/DataConfig/Editor/Json/Configuration.txt\";"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_omits_configuration_marker_when_absent()
		{
			var settings = Settings();
			try
			{
				string source = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>())[SheetXCollectionGenerator.FileName];

				Assert.That(source, Does.Not.Contain("const string Configuration"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_uses_system_only_for_configuration_groups()
		{
			var settings = Settings();
			try
			{
				var groupsOnly = new ConfigSheetData
				{
					Groups = new List<ConfigGroup>
					{
						new ConfigGroup { Key = "economy", ClassName = "Economy" },
					},
				};
				groupsOnly.Groups[0].Fields.Add(new ConfigField { Name = "coins", Type = ConfigFieldType.Int });

				string grouped = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), groupsOnly)["GlobalConfigCollection.cs"];
				string rootOnly = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), RootInt())["GlobalConfigCollection.cs"];

				Assert.That(grouped, Does.Contain("using System;"));
				Assert.That(rootOnly, Does.Not.Contain("using System;"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_uses_unityengine_only_for_configuration_vectors()
		{
			var settings = Settings();
			try
			{
				string vector = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration())["GlobalConfigCollection.cs"];
				string scalar = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), RootInt())["GlobalConfigCollection.cs"];

				Assert.That(vector, Does.Contain("using UnityEngine;"));
				Assert.That(scalar, Does.Not.Contain("using UnityEngine;"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_supports_configuration_only_source_set()
		{
			var settings = Settings();
			try
			{
				settings.collections.Add(new SheetXCollectionDefinition { name = "Shop" });
				var files = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration());

				Assert.That(files.Keys, Is.EqualTo(new[]
				{
					"SheetXDataCollections.cs",
					"GlobalConfigCollection.cs",
					"ShopConfigCollection.cs",
				}));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_is_deterministic_for_configuration()
		{
			var settings = Settings();
			try
			{
				var first = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration());
				var second = SheetXCollectionGenerator.EmitFiles(settings,
					Array.Empty<SheetXCollectionGeneratedTable>(), Configuration());

				Assert.That(second[SheetXCollectionGenerator.FileName], Is.EqualTo(first[SheetXCollectionGenerator.FileName]));
				Assert.That(second["GlobalConfigCollection.cs"], Is.EqualTo(first["GlobalConfigCollection.cs"]));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_member_matching_global_table()
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.RootFields.Add(new ConfigField { Name = "items", Type = ConfigFieldType.Int, SourceId = "config.xlsx", Row = 2 });

				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[] { Existing("a", "Items", "Global", "items", "ItemRow") }, config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("Global table field 'items'")
						.And.Message.Contains("config.xlsx:2")
						.And.Message.Contains("First owner:")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_member_matching_feature_reference()
		{
			var settings = Settings();
			try
			{
				settings.collections.Add(new SheetXCollectionDefinition { name = "Shop" });
				var config = new ConfigSheetData();
				config.RootFields.Add(new ConfigField { Name = "shop", Type = ConfigFieldType.Int, SourceId = "config.xlsx", Row = 2 });

				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("feature collection reference 'Shop'")
						.And.Message.Contains("source 'config.xlsx'")
						.And.Message.Contains("row 2")
						.And.Message.Contains("First owner:")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_type_matching_generated_row_type()
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.Groups.Add(new ConfigGroup { Key = "shopItemsSX", ClassName = "ShopItemsSX", SourceId = "config.xlsx", Row = 2 });

				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[] { Generated("a", "ShopItems", "Global", "shopItems", "id:int") }, config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("ShopItemsSX")
						.And.Message.Contains("Configuration:config.xlsx:2")
						.And.Message.Contains("First owner:")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[TestCase("IsLoaded")]
		[TestCase("SetLoaded")]
		[TestCase("ResetLoaded")]
		[TestCase("Instance")]
		[TestCase("SetInstance")]
		public void emit_files_rejects_configuration_member_matching_inherited_global_contract(string memberName)
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.RootFields.Add(new ConfigField { Name = memberName, Type = ConfigFieldType.Int, SourceId = "config.xlsx", Row = 2 });

				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains(memberName)
						.And.Message.Contains("source 'config.xlsx'")
						.And.Message.Contains("row 2")
						.And.Message.Contains("First owner:")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_path_constant_collision()
		{
			var settings = Settings();
			try
			{
				Assert.That(
					() => SheetXCollectionGenerator.Emit(settings, new[] { Existing("a", "Configuration", "Global", "cfg", "Row") }, Configuration()),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("path constant 'Configuration'")
						.And.Message.Contains("First owner: Configuration (configuration.xlsx:2)")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_nested_type_matching_global_collection_type()
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.Groups.Add(new ConfigGroup
				{
					Key = "globalConfigCollection",
					ClassName = "GlobalConfigCollection",
					SourceId = "config.xlsx",
					Row = 2,
				});

				Assert.That(
					() => SheetXCollectionGenerator.Emit(
						settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("GlobalConfigCollection")
						.And.Message.Contains("collection type 'Global'")
						.And.Message.Contains("config.xlsx")
						.And.Message.Contains("row 2")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_group_member_matching_its_nested_type()
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.Groups.Add(new ConfigGroup
				{
					Key = "Economy",
					ClassName = "Economy",
					SourceId = "config.xlsx",
					Row = 2,
				});

				Assert.That(
					() => SheetXCollectionGenerator.Emit(
						settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("Economy")
						.And.Message.Contains("config.xlsx:2")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_root_member_matching_nested_type()
		{
			var settings = Settings();
			try
			{
				var config = new ConfigSheetData();
				config.Groups.Add(new ConfigGroup
				{
					Key = "economy",
					ClassName = "Economy",
					SourceId = "config.xlsx",
					Row = 2,
				});
				config.RootFields.Add(new ConfigField
				{
					Name = "Economy",
					Type = ConfigFieldType.Int,
					SourceId = "config.xlsx",
					Row = 4,
				});

				Assert.That(
					() => SheetXCollectionGenerator.Emit(
						settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("Economy")
						.And.Message.Contains("source 'config.xlsx'")
						.And.Message.Contains("row 4")
						.And.Message.Contains("config.xlsx:2")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void emit_files_rejects_configuration_field_matching_its_containing_type()
		{
			var settings = Settings();
			try
			{
				var group = new ConfigGroup
				{
					Key = "economy",
					ClassName = "Economy",
					SourceId = "config.xlsx",
					Row = 2,
				};
				group.Fields.Add(new ConfigField
				{
					Name = "Economy",
					Type = ConfigFieldType.Int,
					SourceId = "config.xlsx",
					Row = 2,
				});
				var config = new ConfigSheetData();
				config.Groups.Add(group);

				Assert.That(
					() => SheetXCollectionGenerator.Emit(
						settings, Array.Empty<SheetXCollectionGeneratedTable>(), config),
					Throws.TypeOf<InvalidOperationException>()
						.With.Message.Contains("field 'Economy'")
						.And.Message.Contains("containing nested class 'Economy'")
						.And.Message.Contains("config.xlsx:2")
						.And.Message.Contains("Fix:"));
			}
			finally
			{
				ScriptableObject.DestroyImmediate(settings);
			}
		}

		[Test]
		public void google_collection_table_reader_preserves_headers_and_empty_cells()
		{
			IList<IList<object>> values = new List<IList<object>>
			{
				new List<object> { "id:int", "name:string", "enabled:bool" },
				new List<object> { "1", "hero" },
				new List<object> { "2", null, "true" },
			};

			GoogleSheetHandler.ReadCollectionTable(values, out var headers, out var rows);

			Assert.That(headers, Is.EqualTo(new[] { "id:int", "name:string", "enabled:bool" }));
			Assert.That(rows, Has.Count.EqualTo(2));
			Assert.That(rows[0], Is.EqualTo(new[] { "1", "hero", "" }));
			Assert.That(rows[1], Is.EqualTo(new[] { "2", "", "true" }));
		}

		[Test]
		public void session_writes_json_and_source_only_on_flush()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "ExistingTable", SheetXSheetOutputMode.ExistingDataClass,
					typeof(CollectionGenerationExistingRow).AssemblyQualifiedName);

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(
					session.TryAddGeneratedTable(
						SourceId, "GenTable", new[] { "id:int", "name:string" },
						new IReadOnlyList<string>[] { new[] { "1", "hero" } }, out string error),
					Is.True, error);
				Assert.That(
					session.TryAddExistingTable(
						SourceId, "ExistingTable", "[{\"id\":2,\"name\":\"potion\"}]", out error),
					Is.True, error);

				// Nothing may exist yet: a later sheet can still fail and must not leave partial output.
				Assert.That(File.Exists(GeneratedJson), Is.False);
				Assert.That(File.Exists(ExistingJson), Is.False);
				Assert.That(File.Exists(GeneratedSource), Is.False);
				Assert.That(File.Exists(GlobalCollectionSource), Is.False);

				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(session.WroteArtifacts, Is.True);
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("[{\"id\":1,\"name\":\"hero\"}]"));
				Assert.That(File.ReadAllText(ExistingJson), Is.EqualTo("[{\"id\":2,\"name\":\"potion\"}]"));
				Assert.That(File.ReadAllText(GeneratedSource), Does.Contain("public partial class GenTableSX"));
				string source = File.ReadAllText(GlobalCollectionSource);
				Assert.That(source, Does.Contain("public GenTableSX[] GenTable;"));
				Assert.That(source, Does.Contain(
					"public RCore.SheetX.Tests.CollectionGenerationExistingRow[] ExistingTable;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void successful_flush_removes_legacy_generated_source()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(LegacyGeneratedSource, "// old generated source");
				File.WriteAllText(LegacyGeneratedSource + ".meta", "legacy meta");
				var session = new SheetXCollectionExportSession(settings);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(File.Exists(GeneratedSource), Is.True);
				Assert.That(File.Exists(GlobalCollectionSource), Is.True);
				Assert.That(File.Exists(LegacyGeneratedSource), Is.False);
				Assert.That(File.Exists(LegacyGeneratedSource + ".meta"), Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void final_write_failure_restores_legacy_generated_source()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(LegacyGeneratedSource, "// old generated source");
				var session = new SheetXCollectionExportSession(
					settings, output: new FailingFileOutput(failAfterWrite: 2));

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);

				Assert.That(session.Flush(out error), Is.False);
				Assert.That(File.ReadAllText(LegacyGeneratedSource),
					Is.EqualTo("// old generated source"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void final_write_failure_restores_previous_collection_artifacts()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Directory.CreateDirectory(JsonFolder);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(GeneratedJson, "prior json");
				File.WriteAllText(GeneratedSource, "prior source");
				File.WriteAllText(GlobalCollectionSource, "prior global source");
				var session = new SheetXCollectionExportSession(
					settings, output: new FailingFileOutput(failAfterWrite: 3));

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);

				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("Injected write failure"));
				Assert.That(session.WroteArtifacts, Is.False);
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("prior json"));
				Assert.That(File.ReadAllText(GeneratedSource), Is.EqualTo("prior source"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Is.EqualTo("prior global source"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void session_infers_plain_headers_for_generated_source_and_json()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				var session = new SheetXCollectionExportSession(settings);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id", "price", "enabled", "name" },
					new IReadOnlyList<string>[] { new[] { "1", "1.5", "true", "hero" } },
					out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo(
					"[{\"id\":1,\"price\":1.5,\"enabled\":true,\"name\":\"hero\"}]"));
				Assert.That(File.ReadAllText(GeneratedSource), Does.Contain("public float price;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void session_resolves_ids_before_generated_type_inference()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				var ids = new Dictionary<string, int>();
				var session = new SheetXCollectionExportSession(settings, ids: ids);
				ids["CURRENCY_V_COIN"] = 2;
				ids["ITEM_SWORD"] = 7;

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable",
					new[] { "rewardId", "rewardIds[]", "label", "forced:string" },
					new IReadOnlyList<string>[]
					{
						new[]
						{
							"CURRENCY_V_COIN",
							"CURRENCY_V_COIN|ITEM_SWORD",
							"prefix_CURRENCY_V_COIN",
							"CURRENCY_V_COIN",
						},
					}, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo(
					"[{\"rewardId\":2,\"rewardIds\":[2,7],\"label\":\"prefix_CURRENCY_V_COIN\",\"forced\":\"2\"}]"));
				string source = File.ReadAllText(GeneratedSource);
				Assert.That(source, Does.Contain("public int rewardId;"));
				Assert.That(source, Does.Contain("public int[] rewardIds;"));
				Assert.That(source, Does.Contain("public string forced;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void session_warns_for_keyword_and_preserves_values_after_ignored_columns()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				var warnings = new List<string>();
				var session = new SheetXCollectionExportSession(settings, warnings.Add);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id", "fixed", "note[x]", "name" },
					new IReadOnlyList<string>[] { new[] { "1", "keyword", "ignored", "hero" } },
					out string error), Is.True, error);
				Assert.That(warnings, Has.Count.EqualTo(1));
				Assert.That(warnings[0], Does.Contain(SourceId));
				Assert.That(warnings[0], Does.Contain("GenTable"));
				Assert.That(warnings[0], Does.Contain("Header 'fixed' (column 2)"));
				Assert.That(warnings[0], Does.Contain("C# keyword"));
				Assert.That(warnings[0], Does.Contain("Fix:"));
				Assert.That(warnings[0], Does.Contain("[x]"));

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("[{\"id\":1,\"name\":\"hero\"}]"));
				string source = File.ReadAllText(GeneratedSource);
				Assert.That(source, Does.Contain("public int id;"));
				Assert.That(source, Does.Contain("public string name;"));
				Assert.That(source, Does.Not.Contain("fixed"));
				Assert.That(source, Does.Not.Contain("note"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void rejected_sheet_logs_once_and_is_processed_for_complete_export()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "Broken", SheetXSheetOutputMode.GeneratedDataClass);
				var errors = new List<string>();
				var session = new SheetXCollectionExportSession(settings, null, errors.Add);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "Broken", new[] { "id:long" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out error), Is.False);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "Broken", new[] { "id:long" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out error), Is.False);
				Assert.That(errors, Has.Count.EqualTo(1));

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(errors, Has.Count.EqualTo(1));
				Assert.That(session.FlushSucceeded, Is.True);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void later_generator_collision_skips_only_conflicting_sheet()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "Shop Items", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "other.xlsx", "ShopItems", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "After", SheetXSheetOutputMode.GeneratedDataClass);
				var errors = new List<string>();
				var session = new SheetXCollectionExportSession(settings, null, errors.Add);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "Shop Items", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);
				Assert.That(session.TryAddGeneratedTable(
					"other.xlsx", "ShopItems", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "2" } }, out error), Is.True, error);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "After", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "3" } }, out error), Is.True, error);

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(errors, Has.Count.EqualTo(1));
				Assert.That(errors[0], Does.Contain("other.xlsx"));
				Assert.That(errors[0], Does.Contain("ShopItems"));
				Assert.That(errors[0], Does.Contain("Fix:"));
				Assert.That(session.SkippedSheetCount, Is.EqualTo(1));
				string source = File.ReadAllText(GeneratedSource);
				Assert.That(source, Does.Contain("ShopItemsSX"));
				Assert.That(source, Does.Contain("AfterSX"));
				Assert.That(File.Exists(JsonFolder + "/ShopItems.txt"), Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void partial_collection_export_ignores_bindings_from_another_source()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "other-book.xlsx", "OtherTable", SheetXSheetOutputMode.GeneratedDataClass);

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("[{\"id\":1}]"));
				string source = File.ReadAllText(GeneratedSource);
				Assert.That(source, Does.Contain("GenTableSX"));
				Assert.That(source, Does.Not.Contain("OtherTableSX"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void partial_collection_export_from_same_source_keeps_previous_generated_source()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "OtherTable", SheetXSheetOutputMode.GeneratedDataClass);

				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(GeneratedSource, "// prior source");

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out string error), Is.True, error);

				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("OtherTable"));
				Assert.That(File.Exists(GeneratedJson), Is.False);
				Assert.That(File.ReadAllText(GeneratedSource), Is.EqualTo("// prior source"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void existing_only_session_does_not_require_script_reload()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "ExistingTable", SheetXSheetOutputMode.ExistingDataClass,
					typeof(CollectionGenerationExistingRow).AssemblyQualifiedName);
				Directory.CreateDirectory(CodeFolder);
				foreach (var file in SheetXCollectionGenerator.EmitFiles(settings,
					new[] { Existing(SourceId, "ExistingTable", "Global", "ExistingTable",
						typeof(CollectionGenerationExistingRow).FullName) }))
				{
					File.WriteAllText(CodeFolder + "/" + file.Key, file.Value);
				}

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddExistingTable(
					SourceId, "ExistingTable", "[{\"id\":2,\"name\":\"potion\"}]", out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(session.RequiresScriptReload, Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void existing_table_with_an_unmarked_row_type_is_rejected()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "ExistingTable", SheetXSheetOutputMode.ExistingDataClass,
					typeof(UnmarkedBakeRow).AssemblyQualifiedName);

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.TryAddExistingTable(
					SourceId, "ExistingTable", "[{\"id\":2,\"name\":\"potion\"}]", out string error), Is.False);
				Assert.That(error, Does.Contain("SheetXBindable"));
				Assert.That(error, Does.Contain("UnmarkedBakeRow"));
				Assert.That(session.SkippedSheetCount, Is.EqualTo(1));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void session_ignores_a_json_only_sheet()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "RawData", SheetXSheetOutputMode.JsonOnly);

				var session = new SheetXCollectionExportSession(settings);

				// False with no error: the sheet is not a collection sheet, which is not a failure.
				Assert.That(
					session.TryAddGeneratedTable(
						SourceId, "RawData", new[] { "id:int" },
						new IReadOnlyList<string>[] { new[] { "1" } }, out string error),
					Is.False);
				Assert.That(error, Is.Null);
				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(session.WroteArtifacts, Is.False);
				Assert.That(Directory.Exists(JsonFolder), Is.False);
				Assert.That(File.Exists(GeneratedSource), Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void empty_collection_namespace_falls_back_to_namespace()
		{
			var settings = SessionSettings();
			try
			{
				settings.collectionNamespace = "";
				settings.@namespace = "Game.DataConfig";

				var session = new SheetXCollectionExportSession(settings);

				Assert.That(session.Flush(out string error), Is.True, error);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void bad_schema_skips_one_sheet_and_writes_valid_sheets()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "Broken", SheetXSheetOutputMode.GeneratedDataClass);
				Bind(settings, "AfterBroken", SheetXSheetOutputMode.GeneratedDataClass);

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(
					session.TryAddGeneratedTable(
						SourceId, "GenTable", new[] { "id:int", "name:string" },
						new IReadOnlyList<string>[] { new[] { "1", "hero" } }, out string error),
					Is.True, error);
				Assert.That(
					session.TryAddGeneratedTable(
						SourceId, "Broken", new[] { "id:long" },
						new IReadOnlyList<string>[] { new[] { "1" } }, out error),
					Is.False);
				Assert.That(error, Does.Contain(SourceId));
				Assert.That(error, Does.Contain("Broken"));
				Assert.That(error, Does.Contain("Header 'id:long' (column 1)"));
				Assert.That(error, Does.Contain("Fix:"));
				Assert.That(error, Does.Contain("previous JSON was not updated"));
				Assert.That(
					session.TryAddGeneratedTable(
						SourceId, "AfterBroken", new[] { "id:int" },
						new IReadOnlyList<string>[] { new[] { "2" } }, out error),
					Is.True, error);

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(session.WroteArtifacts, Is.True);
				Assert.That(session.SkippedSheetCount, Is.EqualTo(1));
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("[{\"id\":1,\"name\":\"hero\"}]"));
				Assert.That(File.Exists(JsonFolder + "/Broken.txt"), Is.False);
				Assert.That(File.ReadAllText(JsonFolder + "/AfterBroken.txt"), Is.EqualTo("[{\"id\":2}]"));
				string source = File.ReadAllText(GeneratedSource);
				Assert.That(source, Does.Contain("GenTableSX"));
				Assert.That(source, Does.Contain("AfterBrokenSX"));
				Assert.That(source, Does.Not.Contain("class BrokenSX"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void all_bad_sheets_flush_as_no_op()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "Broken", SheetXSheetOutputMode.GeneratedDataClass);
				var session = new SheetXCollectionExportSession(settings);

				Assert.That(session.TryAddGeneratedTable(
					SourceId, "Broken", new[] { "id:long" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out _), Is.False);

				Assert.That(session.Flush(out string error), Is.True, error);
				Assert.That(session.SkippedSheetCount, Is.EqualTo(1));
				Assert.That(session.WroteArtifacts, Is.False);
				Assert.That(File.Exists(GeneratedSource), Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_is_staged_until_flush()
		{
			var settings = SessionSettings();
			try
			{
				var session = new SheetXCollectionExportSession(settings);
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "general", "timeout", "int", "5" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.False);
				Assert.That(File.Exists(GlobalCollectionSource), Is.False);

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(session.WroteArtifacts, Is.True);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.True);
				string globalSource = File.ReadAllText(GlobalCollectionSource);
				Assert.That(globalSource, Does.Contain("public General general;"));
				Assert.That(globalSource, Does.Contain("public int timeout;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_only_flush_writes_full_source_set_and_json()
		{
			var settings = SessionSettings();
			try
			{
				var session = new SheetXCollectionExportSession(settings);
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "economy", "rate", "float", "1.5" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);

				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.True);
				Assert.That(File.Exists(GeneratedSource), Is.True);
				Assert.That(File.Exists(GlobalCollectionSource), Is.True);
				Assert.That(File.ReadAllText(GeneratedSource), Does.Contain(
					"internal const string Configuration = \"Assets/SheetXTestsTemp/Editor/Json/Configuration.txt\";"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_and_tables_flush_as_one_transaction()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				var session = new SheetXCollectionExportSession(settings);
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "meta", "name", "string", "Game" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out error), Is.True, error);

				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.True);
				Assert.That(File.Exists(GeneratedJson), Is.True);
				string globalSource = File.ReadAllText(GlobalCollectionSource);
				Assert.That(globalSource, Does.Contain("public GenTableSX[] GenTable;"));
				Assert.That(globalSource, Does.Contain("public Meta meta;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void stale_configuration_binding_does_not_block_configuration_flush()
		{
			var settings = SessionSettings();
			try
			{
				settings.sheetBindings.Add(new SheetXSheetBinding
				{
					sourceId = SourceId,
					sheetName = "Configuration",
					collectionName = "MissingCollection",
					outputMode = SheetXSheetOutputMode.GeneratedDataClass,
					fieldName = "broken",
				});
				var session = new SheetXCollectionExportSession(settings);
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "economy", "rate", "float", "1.5" },
				};

				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.True);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_does_not_require_unprocessed_ordinary_binding_from_same_source()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "UncheckedTable", SheetXSheetOutputMode.GeneratedDataClass);
				var session = new SheetXCollectionExportSession(settings);
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "economy", "rate", "float", "1.5" },
				};

				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.True, error);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.True);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_collision_with_global_table_aborts_complete_flush()
		{
			var settings = SessionSettings();
			try
			{
				Bind(settings, "GenTable", SheetXSheetOutputMode.GeneratedDataClass);
				settings.sheetBindings.Single(binding => binding.sheetName == "GenTable").fieldName = "Economy";
				Directory.CreateDirectory(JsonFolder);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(JsonFolder + "/Configuration.txt", "prior config json");
				File.WriteAllText(GeneratedJson, "prior table json");
				File.WriteAllText(GeneratedSource, "prior source");
				File.WriteAllText(GlobalCollectionSource, "prior global");

				var session = new SheetXCollectionExportSession(settings);
				var configuration = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "economy", "rate", "float", "1.5" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, configuration, out string error), Is.True, error);
				Assert.That(session.TryAddGeneratedTable(
					SourceId, "GenTable", new[] { "id:int" },
					new IReadOnlyList<string>[] { new[] { "1" } }, out error), Is.True, error);

				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("Economy"));
				Assert.That(session.SkippedSheetCount, Is.EqualTo(0));
				Assert.That(File.ReadAllText(JsonFolder + "/Configuration.txt"), Is.EqualTo("prior config json"));
				Assert.That(File.ReadAllText(GeneratedJson), Is.EqualTo("prior table json"));
				Assert.That(File.ReadAllText(GeneratedSource), Is.EqualTo("prior source"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Is.EqualTo("prior global"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void invalid_configuration_leaves_previous_files_untouched()
		{
			var settings = SessionSettings();
			try
			{
				Directory.CreateDirectory(JsonFolder);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(JsonFolder + "/Configuration.txt", "prior config json");
				File.WriteAllText(GeneratedSource, "prior source");
				File.WriteAllText(GlobalCollectionSource, "prior global");

				var session = new SheetXCollectionExportSession(settings);
				var badTable = new[]
				{
					new[] { "Wrong", "Header" },
					new[] { "a", "b" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, badTable, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("Configuration"));

				Assert.That(File.ReadAllText(JsonFolder + "/Configuration.txt"), Is.EqualTo("prior config json"));
				Assert.That(File.ReadAllText(GeneratedSource), Is.EqualTo("prior source"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Is.EqualTo("prior global"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void configuration_write_failure_rolls_back_json_and_every_generated_script()
		{
			var settings = SessionSettings();
			try
			{
				Directory.CreateDirectory(JsonFolder);
				Directory.CreateDirectory(CodeFolder);
				File.WriteAllText(JsonFolder + "/Configuration.txt", "prior config json");
				File.WriteAllText(GeneratedSource, "prior source");
				File.WriteAllText(GlobalCollectionSource, "prior global");

				var session = new SheetXCollectionExportSession(
					settings, output: new FailingFileOutput(failAfterWrite: 2));
				var table = new[]
				{
					new[] { "Sub Class", "Field Name", "Type", "Value" },
					new[] { "general", "timeout", "int", "5" },
				};
				Assert.That(session.TryAddConfiguration(SourceId, table, out string error), Is.True, error);
				Assert.That(session.Flush(out error), Is.False);
				Assert.That(error, Does.Contain("Injected write failure"));

				Assert.That(File.ReadAllText(JsonFolder + "/Configuration.txt"), Is.EqualTo("prior config json"));
				Assert.That(File.ReadAllText(GeneratedSource), Is.EqualTo("prior source"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Is.EqualTo("prior global"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void removing_configuration_regenerates_source_without_members_or_marker()
		{
			var settings = SessionSettings();
			try
			{
				Directory.CreateDirectory(CodeFolder);
				foreach (var source in SheetXCollectionGenerator.EmitFiles(
					settings, Array.Empty<SheetXCollectionGeneratedTable>(), Configuration()))
				{
					File.WriteAllText(CodeFolder + "/" + source.Key, source.Value);
				}

				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.Flush(out string error), Is.True, error);
				Assert.That(session.WroteArtifacts, Is.True);
				Assert.That(File.ReadAllText(GeneratedSource), Does.Not.Contain("const string Configuration"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Does.Not.Contain("public class Economy"));
				Assert.That(File.ReadAllText(GlobalCollectionSource), Does.Not.Contain("public Economy economy;"));
			}
			finally
			{
				Cleanup(settings);
			}
		}

		[Test]
		public void no_configuration_and_no_accepted_tables_remains_no_op()
		{
			var settings = SessionSettings();
			try
			{
				var session = new SheetXCollectionExportSession(settings);
				Assert.That(session.Flush(out string error), Is.True, error);
				Assert.That(session.WroteArtifacts, Is.False);
				Assert.That(File.Exists(JsonFolder + "/Configuration.txt"), Is.False);
			}
			finally
			{
				Cleanup(settings);
			}
		}

		private sealed class FailingFileOutput : ISheetXOutput
		{
			private readonly int m_failAfterWrite;
			private int m_writeCount;

			internal FailingFileOutput(int failAfterWrite)
			{
				m_failAfterWrite = failAfterWrite;
			}

			public void Write(string relativePath, string content)
			{
				m_writeCount++;
				SheetXHelper.WriteFile(
					Path.GetDirectoryName(relativePath) ?? "", Path.GetFileName(relativePath), content);
				if (m_writeCount == m_failAfterWrite)
					throw new IOException("Injected write failure");
			}
		}

		private const string TempFolder = "Assets/SheetXTestsTemp";
		private const string CodeFolder = TempFolder + "/Code";
		private const string JsonFolder = TempFolder + "/Editor/Json";
		private const string SourceId = "book.xlsx";
		private const string GeneratedJson = JsonFolder + "/GenTable.txt";
		private const string ExistingJson = JsonFolder + "/ExistingTable.txt";
		private const string CodeFile = "/" + SheetXCollectionGenerator.FileName;
		private const string GeneratedSource = CodeFolder + CodeFile;
		private const string GlobalCollectionSource = CodeFolder + "/GlobalConfigCollection.cs";
		private const string LegacyGeneratedSource = CodeFolder + "/SheetXDataCollections.g.cs";

		private static SheetXSettings SessionSettings()
		{
			var settings = ScriptableObject.CreateInstance<SheetXSettings>();
			settings.ResetToDefault();
			settings.enableCollections = true;
			settings.collectionNamespace = "Game.DataConfig";
			settings.collectionCodeFolder = CodeFolder;
			settings.collectionAssetFolder = TempFolder + "/Collections";
			settings.collectionJsonFolder = JsonFolder;
			settings.globalResourcesFolder = TempFolder + "/Resources";
			return settings;
		}

		private static void Bind(
			SheetXSettings settings, string sheetName, SheetXSheetOutputMode mode, string rowTypeName = null)
			=> Bind(settings, SourceId, sheetName, mode, rowTypeName);

		private static void Bind(
			SheetXSettings settings, string sourceId, string sheetName,
			SheetXSheetOutputMode mode, string rowTypeName = null)
		{
			var binding = SheetXCollectionSettings.GetOrCreateBinding(settings, sourceId, sheetName);
			binding.outputMode = mode;
			binding.rowTypeName = rowTypeName;
		}

		private static void Cleanup(SheetXSettings settings)
		{
			ScriptableObject.DestroyImmediate(settings);
			// Only this test's own folder: the session writes real files through SheetXFileOutput.
			if (Directory.Exists(TempFolder))
				Directory.Delete(TempFolder, true);
			if (File.Exists(TempFolder + ".meta"))
				File.Delete(TempFolder + ".meta");
			AssetDatabase.Refresh();
		}

		private static SheetXSettings Settings()
		{
			var settings = ScriptableObject.CreateInstance<SheetXSettings>();
			settings.ResetToDefault();
			settings.collectionNamespace = "Game.DataConfig";
			settings.collectionJsonFolder = "Assets/Game/DataConfig/Editor/Json";
			return settings;
		}

		private static ConfigSheetData Configuration()
		{
			var data = new ConfigSheetData();
			var group = new ConfigGroup
			{
				Key = "economy",
				ClassName = "Economy",
				SourceId = "configuration.xlsx",
				Row = 2,
			};
			group.Fields.Add(new ConfigField
			{
				Name = "startingCoins",
				Type = ConfigFieldType.Int,
				SourceId = "configuration.xlsx",
				Row = 2,
			});
			data.Groups.Add(group);
			data.RootFields.Add(new ConfigField
			{
				Name = "position2",
				Type = ConfigFieldType.Vector2,
				SourceId = "configuration.xlsx",
				Row = 4,
			});
			return data;
		}

		private static ConfigSheetData RootInt()
		{
			var data = new ConfigSheetData();
			data.RootFields.Add(new ConfigField
			{
				Name = "version",
				Type = ConfigFieldType.Int,
				SourceId = "configuration.xlsx",
				Row = 2,
			});
			return data;
		}

		private static SheetXCollectionGeneratedTable Generated(
			string sourceId, string sheetName, string collectionName, string fieldName, params string[] headers)
		{
			bool ok = SheetXCollectionSchemaParser.TryParse(
				headers,
				SheetXCollectionNaming.RowTypeName(sheetName),
				out var schema,
				out var error);
			Assert.That(ok, Is.True, error);
			return new SheetXCollectionGeneratedTable
			{
				SourceId = sourceId,
				SheetName = sheetName,
				CollectionName = collectionName,
				FieldName = fieldName,
				Schema = schema,
			};
		}

		private static SheetXCollectionGeneratedTable Existing(
			string sourceId, string sheetName, string collectionName, string fieldName, string rowTypeName)
		{
			return new SheetXCollectionGeneratedTable
			{
				SourceId = sourceId,
				SheetName = sheetName,
				CollectionName = collectionName,
				FieldName = fieldName,
				ExistingRowTypeName = rowTypeName,
			};
		}

		private static int IndexOf(string source, string value)
		{
			int index = source.IndexOf(value, StringComparison.Ordinal);
			Assert.That(index, Is.GreaterThanOrEqualTo(0), value);
			return index;
		}
	}
}
