/***
 * Copyright (c) 2018 HNB-RaBear
 * https://github.com/hnb-rabear
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RCore.SheetX.Editor
{
	/// <summary>
	/// One collection-bound sheet that reached the generator: its identity, where it writes, and either
	/// a parsed generated schema or the name of an existing row type.
	/// </summary>
	internal sealed class SheetXCollectionGeneratedTable
	{
		internal string SourceId;
		internal string SheetName;
		internal string CollectionName;
		internal string FieldName;
		internal SheetXCollectionSchema Schema;
		internal string ExistingRowTypeName;
		/// <summary>Filled in by <see cref="SheetXCollectionGenerator.Emit"/> so callers stage the file the constant names.</summary>
		internal string JsonPath;

		/// <summary>The compiled element type of the collection field.</summary>
		internal string RowTypeName => Schema != null ? Schema.RowTypeName : ExistingRowTypeName;
	}

	/// <summary>
	/// Emits the single data-only <c>SheetXDataCollections.cs</c>. Fields only: no runtime loading, no
	/// lookups, no editor types — the baked asset carries the data, so generated code carries no behaviour.
	/// </summary>
	internal static class SheetXCollectionGenerator
	{
		internal const string FileName = "SheetXDataCollections.cs";
		internal const string LegacyFileName = "SheetXDataCollections.g.cs";

		private const string NL = "\r\n";
		private const string T = "\t";

		/// <summary>
		/// Rebuilds the JSON source path for one sheet from settings. The only place that path is derived,
		/// so the generated constant and the baker can never disagree.
		/// </summary>
		internal static string JsonPathFor(SheetXSettings settings, string sheetName)
		{
			string folder = SheetXCollectionSettings.NormalizePath(settings?.ResolveCollectionJsonFolder());
			string file = SheetXCollectionNaming.NormalizeFileName(sheetName) + ".txt";
			return string.IsNullOrEmpty(folder) ? file : folder + "/" + file;
		}

		/// <summary>
		/// Emits the generated data source, or throws <see cref="InvalidOperationException"/> on a name
		/// collision. Use <see cref="EmitFiles"/> when writing output so each collection gets its matching script.
		/// </summary>
		internal static string Emit(SheetXSettings settings, IReadOnlyList<SheetXCollectionGeneratedTable> tables)
			=> EmitFiles(settings, tables)[FileName];

		/// <summary>
		/// Emits row models and paths in <see cref="FileName"/>, plus one matching script per collection type.
		/// </summary>
		internal static IReadOnlyDictionary<string, string> EmitFiles(
			SheetXSettings settings, IReadOnlyList<SheetXCollectionGeneratedTable> tables)
		{
			var ordered = Order(tables);
			foreach (var table in ordered)
				table.JsonPath = JsonPathFor(settings, table.SheetName);
			Validate(settings, ordered);

			var files = new Dictionary<string, string>(StringComparer.Ordinal);
			var dataSource = BeginSource(settings, includeSystem: true);
			string indent = SourceIndent(settings);
			foreach (var table in ordered.Where(t => t.Schema != null))
				AppendRowTypes(dataSource, indent, table.Schema);
			AppendPaths(dataSource, indent, settings, ordered);
			EndSource(dataSource, settings);
			files.Add(FileName, dataSource.ToString());

			var collectionOrder = CollectionOrder(settings, ordered);
			foreach (string collection in collectionOrder)
			{
				var collectionSource = BeginSource(settings, includeSystem: false);
				AppendCollection(collectionSource, indent, collection, collectionOrder, ordered);
				EndSource(collectionSource, settings);
				string typeName = SheetXCollectionNaming.CollectionTypeName(collection);
				files.Add(typeName + ".cs", collectionSource.ToString());
			}
			return files;
		}

		private static StringBuilder BeginSource(SheetXSettings settings, bool includeSystem)
		{
			var source = new StringBuilder();
			source.Append("/***").Append(NL);
			source.Append(" * This script is automatically generated by SheetX.").Append(NL);
			source.Append(" ***/").Append(NL);
			if (includeSystem)
				source.Append("using System;").Append(NL);
			source.Append("using RCore.SheetX;").Append(NL);
			if (includeSystem)
				source.Append("using UnityEngine;").Append(NL);
			source.Append(NL);

			string collectionNamespace = settings?.ResolveCollectionNamespace();
			if (!string.IsNullOrWhiteSpace(collectionNamespace))
			{
				source.Append("namespace ").Append(collectionNamespace.Trim()).Append(NL);
				source.Append('{').Append(NL);
			}
			return source;
		}

		private static string SourceIndent(SheetXSettings settings)
			=> string.IsNullOrWhiteSpace(settings?.ResolveCollectionNamespace()) ? "" : T;

		private static void EndSource(StringBuilder source, SheetXSettings settings)
		{
			if (!string.IsNullOrWhiteSpace(settings?.ResolveCollectionNamespace()))
				source.Append('}').Append(NL);
		}

		private static List<SheetXCollectionGeneratedTable> Order(IReadOnlyList<SheetXCollectionGeneratedTable> tables)
		{
			return (tables ?? Array.Empty<SheetXCollectionGeneratedTable>())
				.Where(t => t != null)
				.OrderBy(t => IsGlobal(t.CollectionName) ? 0 : 1)
				.ThenBy(t => t.CollectionName, StringComparer.Ordinal)
				.ThenBy(t => t.SourceId, StringComparer.Ordinal)
				.ThenBy(t => t.SheetName, StringComparer.Ordinal)
				.ToList();
		}

		private static List<string> CollectionOrder(
			SheetXSettings settings, List<SheetXCollectionGeneratedTable> tables)
		{
			var names = (settings?.collections ?? new List<SheetXCollectionDefinition>())
				.Where(collection => collection != null && !IsGlobal(collection.name))
				.Select(collection => collection.name)
				.Concat(tables.Select(table => table.CollectionName).Where(name => !IsGlobal(name)))
				.Distinct(StringComparer.Ordinal)
				.OrderBy(name => name, StringComparer.Ordinal)
				.ToList();
			// Global always exists: it is the composition root and holds the feature references.
			names.Insert(0, SheetXCollectionSettings.GlobalName);
			return names;
		}

		private static void Validate(
			SheetXSettings settings, List<SheetXCollectionGeneratedTable> tables)
		{
			var rowTypes = new Dictionary<string, string>(StringComparer.Ordinal);
			var declaredTypes = new Dictionary<string, string>(StringComparer.Ordinal);
			var fields = new HashSet<string>(StringComparer.Ordinal);
			var constants = new Dictionary<string, string>(StringComparer.Ordinal);
			var collectionTypes = new Dictionary<string, string>(StringComparer.Ordinal);

			foreach (string collection in CollectionOrder(settings, tables))
			{
				string typeName = SheetXCollectionNaming.CollectionTypeName(collection);
				if (collectionTypes.TryGetValue(typeName, out string owner))
					throw new InvalidOperationException($"Collections '{owner}' and '{collection}' both generate type '{typeName}'.");
				collectionTypes[typeName] = collection;
			}
			declaredTypes["SheetXCollectionPaths"] = "<path constants>";
			var globalFeatureFields = new HashSet<string>(
				CollectionOrder(settings, tables).Where(name => !IsGlobal(name)).Select(SheetXCollectionNaming.ToCamelIdentifier),
				StringComparer.Ordinal);

			foreach (var table in tables)
			{
				if (string.IsNullOrEmpty(table.RowTypeName))
					throw new InvalidOperationException($"Sheet '{table.SheetName}' has no row type.");
				if (string.IsNullOrEmpty(table.FieldName))
					throw new InvalidOperationException($"Sheet '{table.SheetName}' has no collection field name.");

				// Only generated rows declare a type; an Existing Data Class reuses one the developer owns.
				if (table.Schema != null)
				{
					if (rowTypes.TryGetValue(table.RowTypeName, out string owner))
					{
						throw new InvalidOperationException(
							$"Sheets '{owner}' and '{table.SheetName}' both generate row type '{table.RowTypeName}'.");
					}
					rowTypes[table.RowTypeName] = table.SheetName;

					// Row and nested classes share one namespace, so a repeated name is a duplicate declaration.
					foreach (string declared in new[] { table.RowTypeName }.Concat(table.Schema.Objects.Select(o => o.TypeName)))
					{
						if (declaredTypes.TryGetValue(declared, out string first))
						{
							throw new InvalidOperationException(
								$"Sheets '{first}' and '{table.SheetName}' both generate type '{declared}'.");
						}
						if (collectionTypes.ContainsKey(declared))
							throw new InvalidOperationException($"Generated type '{declared}' collides with a generated collection type.");
						declaredTypes[declared] = table.SheetName;
					}
				}

				if (!fields.Add(table.CollectionName + "\0" + table.FieldName))
				{
					throw new InvalidOperationException(
						$"Collection '{table.CollectionName}' declares field '{table.FieldName}' twice.");
				}
				if (IsGlobal(table.CollectionName) && globalFeatureFields.Contains(table.FieldName))
				{
					throw new InvalidOperationException(
						$"Global table field '{table.FieldName}' collides with a feature collection reference.");
				}

				string constant = SheetXCollectionNaming.ToPascalIdentifier(table.SheetName);
				if (constants.TryGetValue(constant, out string existing))
				{
					throw new InvalidOperationException(
						$"Sheets '{existing}' and '{table.SheetName}' both generate path constant '{constant}'.");
				}
				constants[constant] = table.SheetName;
			}
		}

		private static void AppendRowTypes(StringBuilder source, string indent, SheetXCollectionSchema schema)
		{
			AppendSerializableClass(source, indent, schema.RowTypeName, MembersOf(schema, Array.Empty<string>()));
			foreach (var nested in schema.Objects)
				AppendSerializableClass(source, indent, nested.TypeName, MembersOf(schema, nested.Path));
		}

		// Members directly under one object path: leaf columns plus one field per immediate child object.
		private static IEnumerable<string> MembersOf(SheetXCollectionSchema schema, IReadOnlyList<string> parent)
		{
			var members = new List<string>();
			foreach (var column in schema.Columns)
			{
				if (column.Path.Count == parent.Count + 1 && StartsWith(column.Path, parent))
					members.Add($"public {column.TypeName} {column.FieldName};");
			}
			foreach (var nested in schema.Objects)
			{
				if (nested.Path.Count == parent.Count + 1 && StartsWith(nested.Path, parent))
					members.Add($"public {nested.TypeName} {nested.FieldName};");
			}
			return members;
		}

		private static bool StartsWith(IReadOnlyList<string> path, IReadOnlyList<string> prefix)
		{
			for (int i = 0; i < prefix.Count; i++)
			{
				if (!string.Equals(path[i], prefix[i], StringComparison.Ordinal))
					return false;
			}
			return true;
		}

		private static void AppendSerializableClass(
			StringBuilder source, string indent, string typeName, IEnumerable<string> members)
		{
			source.Append(indent).Append("[Serializable]").Append(NL);
			source.Append(indent).Append("public partial class ").Append(typeName).Append(NL);
			source.Append(indent).Append('{').Append(NL);
			foreach (string member in members)
				source.Append(indent).Append(T).Append(member).Append(NL);
			source.Append(indent).Append('}').Append(NL).Append(NL);
		}

		private static void AppendCollection(
			StringBuilder source, string indent, string collection,
			IEnumerable<string> collectionOrder, List<SheetXCollectionGeneratedTable> tables)
		{
			bool global = IsGlobal(collection);
			string baseType = global ? "GlobalConfigCollectionBase" : "SheetXConfigCollectionBase";
			source.Append(indent).Append("public partial class ")
				.Append(SheetXCollectionNaming.CollectionTypeName(collection))
				.Append(" : ").Append(baseType).Append(NL);
			source.Append(indent).Append('{').Append(NL);

			foreach (var table in tables.Where(t => string.Equals(t.CollectionName, collection, StringComparison.Ordinal)))
				source.Append(indent).Append(T).Append("public ").Append(table.RowTypeName).Append("[] ").Append(table.FieldName).Append(';').Append(NL);

			if (global)
			{
				// The Global asset is the composition root: it holds a reference to every feature collection.
				foreach (string feature in collectionOrder.Where(name => !IsGlobal(name)))
				{
					source.Append(indent).Append(T).Append("public ")
						.Append(SheetXCollectionNaming.CollectionTypeName(feature)).Append(' ')
						.Append(SheetXCollectionNaming.ToCamelIdentifier(feature)).Append(';').Append(NL);
				}
			}
			source.Append(indent).Append('}').Append(NL).Append(NL);
		}

		private static void AppendPaths(
			StringBuilder source, string indent, SheetXSettings settings, List<SheetXCollectionGeneratedTable> tables)
		{
			source.Append(indent).Append("public static partial class SheetXCollectionPaths").Append(NL);
			source.Append(indent).Append('{').Append(NL);
			foreach (var table in tables)
			{
				source.Append(indent).Append(T).Append("internal const string ")
					.Append(SheetXCollectionNaming.ToPascalIdentifier(table.SheetName))
					.Append(" = \"").Append(table.JsonPath).Append("\";").Append(NL);
			}
			source.Append(indent).Append('}').Append(NL);
		}

		private static bool IsGlobal(string collection)
			=> string.Equals(collection, SheetXCollectionSettings.GlobalName, StringComparison.Ordinal);
	}
}
