name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  editorconfig:
    name: EditorConfig compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
        with:
          version: 3.0.3

  yaml:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/"
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                check-keys: false

  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            docs/**/*.md
            CHANGELOG.md
            README.md
          config: |
            {
              "default": true,
              "MD013": false,
              "MD024": { "siblings_only": true },
              "MD033": false,
              "MD041": false
            }
